export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";

export const CREATE_PREMIUM = "CREATE_PREMIUM";
export const LOAD_PREMIUM_SUCCESS = "LOAD_PREMIUM_SUCCESS";
export const CREATE_PREMIUM_SUCCESS = "CREATE_PREMIUM_SUCCESS";
export const UPDATE_PREMIUM_SUCCESS = "UPDATE_PREMIUM_SUCCESS";
export const DELETE_PREMIUM_OPTIMISTIC = "DELETE_PREMIUM_OPTIMISTIC";
